config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"
  
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :index, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image
  
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 } 
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @book = Book.new
      @books = Book.all
      @user = User.find(current_user.id)
      render :index
    end
  end

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(current_user.id)
    @books = @user.books
  end

  def edit
    book = Book.find(params[:id])
    unless book.id == current_user.id
      redirect_to books_path
    end
  end
  
  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to book_path(book.id)
    else
      flash[:notice] = "errors prohibited this obj from being saved:"
      @book = Book.find(params[:id])
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    redirect_to '/books'
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(current_user.id)
    @books = @user.books
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
  
  def update
    user = User.find(params[:id])
    
    if user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(user.id)
    else
      @user = User.find(current_user.id)
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
    <% if @book.errors.any? %>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
        <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
    <div class="row">
        <div class="col mx-auto">
            <h1>Editing Book</h1>
            <%= form_with model: @book, method: :patch do |f| %>
            <div class="form-group">
                <p>Title</p>
                <%= f.text_field :title %>
            </div>
            <div class="form-group">
                <p>Opinion</p>
                <%= f.text_area :body %>
            </div>
            <div class="form-group">
                <%= f.submit 'Update Book' %>
            </div>
            <% end %>
        </div>
    </div>
</div>

<div class="link">
    <span><%= link_to "Show", book_path(@book.id), method: :get %></span>
     |
    <span><%= link_to "Back", books_path, method: :get %></span>
</div>

app/views/books/index.html.erb
<div class="container px-5">

    <div class="row">
        <%= render 'users/user' %>
        <div class="col-md-8 offset-1">
            <h2>Books</h2>
            <table class="table table-hover">
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                </tr>
                <%= @books.each do |book| %>
                <tr>
                    <td><%= image_tag book.user.get_profile_image(100,100) %></td>
                    <td><span><%= link_to book.title, book_path(book.id), method: :get %></span></td>
                    <td><span><%= book.body %></span></td>
                </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="container px-5">
  <div class="row">
    <%= render 'users/user' %>
    <div class="col-md-8 offset-1">
      <h2>Book detail</h2>
      <table class="table table-hover">
        <%= @books.each do |book| %>
          <tr>
            <td><%= image_tag book.user.get_profile_image(100,100) %>
                <%= link_to book.user.name, user_path(book.user.id), method: :get %>
            </td>
            <td><span><%= book.title %></span></td>
            <td><span><%= book.body %></span></td>
            <td>
              <% if book.user == current_user %>
                <%= link_to "Edit", edit_book_path(book.id), method: get %>
              <% end %>
            </td>
            <td>
              <% if book.user == current_user %>
                <%= link_to "Destroy", book_path(book.id), method: delete %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fa-solid fa-book"></i> <strong>Bookers</strong></h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col mx-auto">
      <h1>
        Welcome to <i class="fa-solid fa-book"></i><strong>Bookers!!</strong>
      </h1>
      <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="btn btn-success btn-block sign_up" href="/users/sign_up">Sign up</div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/8b3082863e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <i class="fa-solid fa-house"></i>
                  <%= link_to "Home", user_path(current_user) %>
                </li>
                <li>
                  <i class="fa-solid fa-users"></i>
                  <%= link_to "Users", users_path %>
                </li>
                <li>
                  <i class="fa-solid fa-book-open"></i>
                  <%= link_to "Books", books_path %>
                </li>
                <li>
                  <i class="fa-solid fa-right-from-bracket"></i>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
                <li>
                  <i class="fa-solid fa-house"></i>
                  <%= link_to "Home", root_path %>
                </li>
                <li>
                  <i class="fa-solid fa-link"></i>
                  <%= link_to "About", home_about_path %>
                </li>
                <li>
                  <i class="fa-solid fa-user-plus"></i>
                  <%= link_to "Sign up", new_user_registration_path %>
                </li>
                <li>
                  <i class="fa-solid fa-right-to-bracket"></i>
                  <%= link_to "Log in", new_user_session_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      
        
      
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_user.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag @user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><% @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><% @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <a class="btn btn-outline-primary btn-block" href="/users/:id/edit"><i class="fa-solid fa-user-gear"></i></a>
  </div>
  <h2>New book</h2>
    <%= form_with model: @book, local: true do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <label for="book_body">Opinion</label>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <% if @user.errors.any? %>
    <%= @user.errors.count %>件のエラーが発生しました
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div clss="row">
    <div class="col mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user, method: :patch do |f| %>
      <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
      </dev>
      <div class="form-group">
        <label for="inputImage">Image</label>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
      </div>
      <div class="form-group">
        <label for="inputIntroduction">Introduction</label>
      <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction"%>
      </div>
      <div class="form-group">
        <%= f.submit "Update User" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5">
    <div class="row">
        <%= render 'user' %>
        <div class="col-md-8 offset-1">
            <h2>Users</h2>
            <table class="table table-hover">
                <tr>
                    <th>image</th>
                    <th>name</th>
                    <th></th>
                </tr>
                <%= @users.each do |user| %>
                <tr>
                    <td><%= image_tag user.get_profile_image(100,100) %></td>
                    <td><span><% user.name %></span></td>
                    <td><span><%= link_to "Show", user_path(user.id), method: :get %></span></td>
                </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container px-5">
    <div class="row">
        
          <%= render 'user' %>
          <div class="col-md-8 offset-1">
              <h2>Books</h2>
              <table class="table table-hover">
                  <tr>
                      <th></th>
                      <th>Title</th>
                      <th>Opinion</th>
                      <th colspan="3"></th>
                  </tr>
                  <%= @books.each do |book| %>
                      <tr>
                          <td><%= image_tag book.user.get_profile_image(100,100) %></td>
                          <td><span><%= link_to book.name, book_path(book.id), method: :get %></span></td>
                          <td><span><%= book.body %></span></td>
                          <td>
                              <a class="btn" href="/books/:id/edit">Edit</i></a>
                              <a class="btn　btn-danger" data-confirm="Are you sure?" dete-method="delete" href="/books/:id" rel="nofollow">Destroy</i></a>
                          </td>
                      </tr>
                  <% end %>
              </table>
          </div>
        
    </div>
</div>